###
# @no-cookie-jar
GET {{host-url}}myAccount
Authorization: Basic {{john.basic-auth}}

###
# @no-cookie-jar
GET {{host-url}}myBalance
Authorization: Basic {{john.basic-auth}}

###
# @no-cookie-jar
GET {{host-url}}myCards
Authorization: Basic {{john.basic-auth}}

###
# @no-cookie-jar
GET {{host-url}}contact

###
# @no-cookie-jar
GET {{host-url}}myLoans
Authorization: Basic {{john.basic-auth}}

###
# @no-cookie-jar
GET {{host-url}}notices

###
# @no-cookie-jar
POST {{host-url}}register
Content-Type: application/json

{
  "email": "john@example.com",
  "pwd": "EazyBytes@12345",
  "role": "user"
}